name: Docker image build
on:
  workflow_call:
    inputs:
      name:
        type: string
        default: None

jobs:
  build:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          set -vx
          sudo snap install multipass
          ls -l /var/snap/multipass/common/multipass_socket || true
          journalctl --unit 'snap.multipass*'
          multipass launch -n instance ${{ inputs.name }}
          multipass exec instance cat /etc/pollinate/add-user-agent

