name: Docker image build
on:
  workflow_call:
    inputs:
      name:
        type: string
        default: None

jobs:
  build:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo snap install multipass
