name: Multipass image instance test
on:
  workflow_call:
    inputs:
      name:
        type: string
        default: None

jobs:
  build:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          set -vx
          #sudo apt-get update
          #sudo apt-get install snap
          sudo snap install multipass
          multipass info --all || true
          #sudo systemctl restart snapd
          #sudo snap restart multipass.multipassd
          sudo ls -l /var/snap/multipass/common/multipass_socket || true

          #          sudo find /var/snap/multipass
          #journalctl --unit 'snap.multipass*'
          #sudo snap connections multipass
          sudo cat /var/log/syslog | grep -i 'virt|kvm'
          #multipass launch -n instance ${{ inputs.name }}
          #multipass exec instance cat /etc/pollinate/add-user-agent

