name: Build docker images for HDK
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '51 2 * * *'

jobs:
  ubuntu:
    uses: ./.github/workflows/launch.yml
    with:
      name: ubuntu

  docker:
    name: Build
    uses: ./.github/workflows/launch.yml
    with:
      name: docker

