name: Images in multipass
on:
  workflow_dispatch:
  push:
    #    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '51 2 * * *'

jobs:
  ubuntu:
    uses: ./.github/workflows/launch.yml
    with:
      name: core

  docker:
    name: Build
    uses: ./.github/workflows/launch.yml
    with:
      name: docker

